# Generated by Django 3.2.8 on 2021-10-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_group', models.CharField(max_length=25, verbose_name='Код группы')),
                ('name_group', models.CharField(max_length=250, verbose_name='Тип ткани')),
                ('purpose_group', models.TextField(max_length=50, verbose_name='Назначение')),
                ('anons_group', models.CharField(max_length=250, verbose_name='Анонсы')),
                ('dates', models.DateField(verbose_name='Дата создания')),
                ('url_group', models.URLField(verbose_name='Адрес группы')),
            ],
            options={
                'verbose_name': 'Группы ткане',
                'verbose_name_plural': 'Группа ткани',
            },
        ),
    ]
