# Generated by Django 3.2.8 on 2021-10-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_group', models.CharField(max_length=25, verbose_name='Код группы')),
                ('name_group', models.CharField(max_length=250, verbose_name='Тип дивана')),
                ('purpose_group', models.TextField(blank=True, max_length=250, verbose_name='Назначение, для..')),
                ('photo_group', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_publish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Группы диванов',
                'verbose_name_plural': 'Группа дивана',
            },
        ),
        migrations.AlterModelOptions(
            name='cloth_group',
            options={'verbose_name': 'Группы тканей', 'verbose_name_plural': 'Группа ткани'},
        ),
        migrations.AlterField(
            model_name='cloth_group',
            name='anons_group',
            field=models.CharField(max_length=100, verbose_name='Анонсы'),
        ),
        migrations.AlterField(
            model_name='cloth_group',
            name='purpose_group',
            field=models.TextField(max_length=250, verbose_name='Назначение'),
        ),
    ]
