# Generated by Django 3.2.8 on 2021-11-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211027_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_group',
            options={'verbose_name': 'Модели диванов', 'verbose_name_plural': 'Модель диванов'},
        ),
        migrations.AddField(
            model_name='cloth_group',
            name='main_photo',
            field=models.ImageField(default=1, upload_to='tryweb\\static\tryweb\\images\\cloth\x0belur\x01.jpeg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloth_group',
            name='anons_group',
            field=models.CharField(max_length=100, verbose_name='Коллекции'),
        ),
        migrations.AlterField(
            model_name='model_group',
            name='photo_group',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
