# Generated by Django 3.2.8 on 2021-11-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211130_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azbuka_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.CharField(max_length=25, verbose_name='Код товара')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('availability', models.CharField(max_length=25, verbose_name='availability')),
                ('condition', models.CharField(max_length=25, verbose_name='condition')),
                ('product_category', models.CharField(max_length=35, verbose_name='product_category')),
                ('parent_product_category', models.CharField(max_length=35, verbose_name='parent_product_category')),
                ('price', models.CharField(max_length=25, verbose_name='price')),
                ('sale_price', models.CharField(max_length=25, verbose_name='sale_price')),
                ('image_link', models.URLField(max_length=250, verbose_name='image_link')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='description')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_publish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Товары Азбуки',
                'verbose_name_plural': 'Товар Азбуки',
            },
        ),
        migrations.AlterField(
            model_name='cloth_group',
            name='main_photo',
            field=models.ImageField(upload_to='media\\cloth', verbose_name='Ссылка фото'),
        ),
    ]
