# Generated by Django 3.2.8 on 2021-11-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20211130_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azbuka_items',
            name='is_publish',
        ),
        migrations.RemoveField(
            model_name='azbuka_items',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='azbuka_items',
            name='time_update',
        ),
    ]
