# Generated by Django 3.2.8 on 2021-12-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20211130_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azbuka_items',
            options={'ordering': ['title', 'id'], 'verbose_name': 'Товары Азбуки', 'verbose_name_plural': 'Товар Азбуки'},
        ),
        migrations.AlterField(
            model_name='cloth_group',
            name='main_photo',
            field=models.ImageField(upload_to='media\\cloth_group', verbose_name='Ссылка фото'),
        ),
        migrations.CreateModel(
            name='Cloth_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_item', models.CharField(max_length=25, verbose_name='Код')),
                ('name_item', models.CharField(max_length=250, verbose_name='Тип дивана')),
                ('photo_item', models.ImageField(upload_to='media\\cloth_items', verbose_name='основное фото')),
                ('categor_price', models.CharField(max_length=25, verbose_name='price')),
                ('sale_price', models.CharField(max_length=25, verbose_name='sale_price')),
                ('image_link', models.URLField(max_length=250, verbose_name='image_link')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='description')),
                ('purpose_item', models.TextField(blank=True, max_length=250, verbose_name='Назначение, для..')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('parent_category', models.ManyToManyField(to='catalog.Cloth_group')),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
            },
        ),
    ]
