# Generated by Django 3.2.8 on 2021-12-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20211214_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_color', models.CharField(max_length=25, verbose_name='Код')),
                ('color_main', models.CharField(max_length=25, verbose_name='Основной цвет')),
                ('color_hex', models.CharField(blank=True, max_length=10, verbose_name='HEX')),
                ('is_publish', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Цвет тканей',
                'verbose_name_plural': 'Цвет ткани',
            },
        ),
        migrations.AlterField(
            model_name='cloth_categor_price',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cloth_items',
            name='color_cloth',
            field=models.ManyToManyField(to='catalog.Cloth_color'),
        ),
    ]
