# Generated by Django 3.2.8 on 2021-12-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20211214_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_vendor', models.CharField(max_length=25, verbose_name='Код')),
                ('name_vendor', models.CharField(max_length=50, verbose_name='Поставщик')),
                ('is_publish', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Цвет тканей',
                'verbose_name_plural': 'Цвет ткани',
            },
        ),
    ]
