# Generated by Django 3.2.8 on 2021-12-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth_categor_price',
            options={'ordering': ['categor_price'], 'verbose_name': 'Категории тканей', 'verbose_name_plural': 'Категория ткани'},
        ),
        migrations.AlterModelOptions(
            name='cloth_color',
            options={'ordering': ['color_main'], 'verbose_name': 'Каталог цветов', 'verbose_name_plural': 'Цвет'},
        ),
        migrations.AlterModelOptions(
            name='cloth_group',
            options={'ordering': ['name_group'], 'verbose_name': 'Группы тканей', 'verbose_name_plural': 'Группа ткани'},
        ),
        migrations.AlterModelOptions(
            name='cloth_items',
            options={'ordering': ['name_item'], 'verbose_name': 'Ткань', 'verbose_name_plural': 'Ткани'},
        ),
        migrations.AlterModelOptions(
            name='model_group',
            options={'ordering': ['name_group'], 'verbose_name': 'Модели диванов', 'verbose_name_plural': 'Модель диванов'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name_vendor'], 'verbose_name': 'Поставщика', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='cloth_color',
            name='code_color',
            field=models.CharField(blank=True, max_length=25, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='cloth_group',
            name='anons_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='cloth_group',
            name='code_group',
            field=models.CharField(blank=True, max_length=25, verbose_name='Код группы'),
        ),
        migrations.AlterField(
            model_name='cloth_group',
            name='dates',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cloth_group',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to='media\\cloth_group', verbose_name='Ссылка фото'),
        ),
        migrations.AlterField(
            model_name='cloth_group',
            name='purpose_group',
            field=models.TextField(blank=True, max_length=250, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='cloth_group',
            name='url_group',
            field=models.URLField(blank=True, verbose_name='Адрес группы'),
        ),
    ]
