# Generated by Django 3.2.8 on 2021-12-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20211215_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth_items',
            name='code_item',
            field=models.CharField(max_length=25, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='cloth_items',
            name='photo_item',
            field=models.ImageField(upload_to='media\\cloth_items', verbose_name='основное фото'),
        ),
    ]
