# Generated by Django 3.2.8 on 2021-12-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20211215_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth_items',
            options={'ordering': ['-id'], 'verbose_name': 'Ткань', 'verbose_name_plural': 'Ткани'},
        ),
        migrations.AlterField(
            model_name='cloth_items',
            name='categor_price',
            field=models.ManyToManyField(blank=True, default=0, to='catalog.Cloth_categor_price'),
        ),
        migrations.AlterField(
            model_name='cloth_items',
            name='time_create',
            field=models.DateTimeField(),
        ),
    ]
