# Generated by Django 3.2.8 on 2022-01-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20211217_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_group',
            name='photo_group',
            field=models.ImageField(upload_to='media\\photos'),
        ),
    ]
