# Generated by Django 3.2.8 on 2022-01-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_model_group_photo_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_group',
            name='photo_group',
            field=models.ImageField(upload_to='type_model/'),
        ),
    ]
