# Generated by Django 3.2.8 on 2021-10-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryweb', '0002_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
